[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino

; Wokwi simulates this board over serial + WiFi (Wokwi-GUEST AP with real internet)
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9
    beegee-tokyo/DHT sensor library for ESPx@^1.19
    bblanchon/ArduinoJson@^7.0.4
